sudo: false
language: node_js
node_js:
- '5.0'
env:
  global:
  - DISPLAY=:99.0
  - SAUCE_USERNAME: react-fine-uploader2
  - secure: QW6G2+DfOiH01dRd8qlj/Xc58maGsj7NKge7fIOqBF2SO42RyGAzRCLyeI2A7Sj0lcytIP2X1ILLhNMVsAMa0ldTnBa3hDmonBOvgGmLxbe13EsM+2sfsqAigOiIoUwk5yUk/v4pOCFmEf3BCE9jEp5S0q197Ii8tuH99AO9vKz1wFJ21fZZf9+N8tJcXaBpR7nfeN80G0Fs+ddQktYCq+644CQveqghwx1Vbi2wztkTZKMcSdCYh8pQaieZf2PnIGi/StcOry6jBOlfl8H243vpdmHJJssztHiylomjtPjsxnB5PdwtlZZNIgy/+/cGYcE9RRNwEpOe1Z10NvukSjW/hmYEo8It3xakdYhV3jQU8GTCSxu2D8QyR/pW0JjxDyybmGhE5ElQaGMSUdJ/5+FF/aTuzmfly8eAZX1+64XOZSEwbUi+A2hDZ2HIJU+jaGwXouzUqYCvsjn+tAn2mlURdGCaooqWoCVxpnP2MBFKhRuyL2aX6MgqRkZ1GOHH5SAo/ufPd5j8tRQ7BwEcyX1zit/EiutPhkhsO3fdW2EBs5EjrNxK5x+tFATml1iawdvy2m+h8kvwQ3oA2ja8gGBuIcdYKft+iHGk7ozUxOHvzTVQ1tNlFoM05drNDGn2Ld23j8ih7jtaHb1lAprqUBNodiStBxUIqmsRMO/zwMs=
before_script:
- sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
  jwt:
    secure: adRnCigFL/pHJdZzRtb4cEw2vGsrvqyWKVfR77nhTTPrgk9TiIvPd1/w9ufQJhhYkYtq2TqdWVmuw7wzBYiu2RiTWHeTEDmACUkfJbWPBt9xfUiOOgcNvLKGMICoeKEeiX+yK0FRGv+V6vInyOVCl+yEJ3nH4Rf9a2UbCLZaB/HTnhu8ejjwz7mnklbsGnGHyUi9VRIz24u02lxXVOZrrAQNsNdxDz8Lyu2RGAbFGdN+iw8alRVLhErv0n8TgWm5CUBoon3e1g6gEoXswLqNWrpJXagQeamHaflpehGJ0zubqXohf3OP4hxRD7apeeAvXfT7/O0uQCGnLQAlgH3bHWCx6O9xSshfpfoevnsKlTxMHyIc4hx76yA3picCKwRdtnnJbBOqSIT9/8VAhp3WJxOWbGwp0J44u5E4PjHuL5h5kt0NOFADyysS+/RLG3GZN4VJ9qzFb1uQ4qeJpS5/6iRFiwbS09h/TP8F4XjuY478xuSR4fhUH1qz0EA3R6PRtjRP1nFSOdqH3SZd10rFphUij+uOoDpUaAI5FFqld0+iBO2/hiQEdJSCm+/gk0n+hyqnHJfNIvTMC7OFOKLR2+yWZC4saRNKu/BcIdY9BA/VurQAUykrlwP+bp3GvqTnWCHuRNpNuAoz6h3ITeCq8Rm+ZW5O3JFB4H1EQUf+6L8=
